/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "airports.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

nearest_results_air *
getnearest_air_1(geoLocation *argp, CLIENT *clnt)
{
	static nearest_results_air clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getNearest_air,
		(xdrproc_t) xdr_geoLocation, (caddr_t) argp,
		(xdrproc_t) xdr_nearest_results_air, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
