/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>
#include "kdtree.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef char *nametype_air;

typedef struct airNode_air *airList_air;

struct geoLocation {
	double longitude;
	double latitude;
};
typedef struct geoLocation geoLocation;

struct nearAirport {
	nametype_air code;
	nametype_air name;
	double dist;
	geoLocation loc;
};
typedef struct nearAirport nearAirport;

struct airNode_air {
	nearAirport p;
	airList_air next;
};
typedef struct airNode_air airNode_air;

struct nearest_results_air {
	int err;
	union {
		airList_air x;
	} nearest_results_air_u;
};
typedef struct nearest_results_air nearest_results_air;

typedef struct node {
	char * airportCode;
	char * city;
	char * state;
	struct node * next;
} node_t;

void *kd = NULL;

#define airportProgram 0x12345679
#define airport_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define getNearest_air 1
extern  nearest_results_air * getnearest_air_1(geoLocation *, CLIENT *);
extern  nearest_results_air * getnearest_air_1_svc(geoLocation *, struct svc_req *);
extern int airportprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getNearest_air 1
extern  nearest_results_air * getnearest_air_1();
extern  nearest_results_air * getnearest_air_1_svc();
extern int airportprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype_air (XDR *, nametype_air*);
extern  bool_t xdr_airList_air (XDR *, airList_air*);
extern  bool_t xdr_geoLocation (XDR *, geoLocation*);
extern  bool_t xdr_nearAirport (XDR *, nearAirport*);
extern  bool_t xdr_airNode_air (XDR *, airNode_air*);
extern  bool_t xdr_nearest_results_air (XDR *, nearest_results_air*);

#else /* K&R C */
extern bool_t xdr_nametype_air ();
extern bool_t xdr_airList_air ();
extern bool_t xdr_geoLocation ();
extern bool_t xdr_nearAirport ();
extern bool_t xdr_airNode_air ();
extern bool_t xdr_nearest_results_air ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
