/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"

const int BAD_STATE = -1;
const int UNCLEAR = -2;
const int UNKNOWN = -3;

void
placesprogram_1(char *host, place info)
{
	CLIENT *clnt;
	nearest_results_place  *result_1;
	place getnearest_place_1_arg;
	getnearest_place_1_arg.city = info.city;
	getnearest_place_1_arg.state = info.state;

//Create connection
#ifndef	DEBUG
	clnt = clnt_create (host, placesProgram, places_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//Request to server
	result_1 = getnearest_place_1(&getnearest_place_1_arg, clnt);
	if (result_1 == (nearest_results_place *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{

		//Check possible errors
		if ( result_1->err == 0 ){

			printf("This is 5 closet airports to:\n");
				printf("City:%s\n", 
				result_1->nearest_results_place_u.info.search_location.city);
				printf("State:%s\n", 
				result_1->nearest_results_place_u.info.search_location.state);
			printf("\n");

			printf("Lat=%f, Lon=%f\n", 
				result_1->nearest_results_place_u.info.coord.latitude,
				result_1->nearest_results_place_u.info.coord.longitude);

			//Linked list traversal of nearest
			airList_place walker = result_1->nearest_results_place_u.info.x;
			while(walker)
			{
				printf("Code=%s, ", walker->p.code);
				printf("Name=%s, ", walker->p.name);
				printf("State=%s, ", walker->p.state);
				printf("Distance=%f, \n", walker->p.dist);

				walker = walker->next;
			}

			clnt_freeres (clnt, (xdrproc_t)xdr_nearest_results_place, (char*)result_1);
		} 
		else if (result_1->err == BAD_STATE)
		{
			printf("You input an incorrect State.\n");
		}
		else if (result_1->err == UNCLEAR)
		{
			printf("You need to input a clearer city name.\n");
		}
		else if (result_1->err == UNKNOWN)
		{
			printf("You input an incorrect city\n");
		}
		else 
		{
			printf("There is an error on the server side!!!\n");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	place loc;

	printf("\n\n");

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	loc.city = argv[2];
	loc.state = argv[3];

	placesprogram_1 (host, loc);

	printf("\n\n");

	exit (0);
}
