/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_nametype (XDR *xdrs, nametype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airList_place (XDR *xdrs, airList_place *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct airNode_place), (xdrproc_t) xdr_airNode_place))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geoLocation_place (XDR *xdrs, geoLocation_place *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportInfo (XDR *xdrs, airportInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_nametype (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_nametype (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dist))
		 return FALSE;
	 if (!xdr_geoLocation_place (xdrs, &objp->loc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airNode_place (XDR *xdrs, airNode_place *objp)
{
	register int32_t *buf;

	 if (!xdr_airportInfo (xdrs, &objp->p))
		 return FALSE;
	 if (!xdr_airList_place (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_place (XDR *xdrs, place *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype (xdrs, &objp->city))
		 return FALSE;
	 if (!xdr_nametype (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location_and_airports (XDR *xdrs, location_and_airports *objp)
{
	register int32_t *buf;

	 if (!xdr_airList_place (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_geoLocation_place (xdrs, &objp->coord))
		 return FALSE;
	 if (!xdr_place (xdrs, &objp->search_location))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nearest_results_place (XDR *xdrs, nearest_results_place *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_location_and_airports (xdrs, &objp->nearest_results_place_u.info))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
